# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.0.4
group=com.mod.mozaik
java_version=21

# Common
minecraft_version=1.21.1
mod_name=mozaik
mod_author=zimzelens & jodi/jodlodi
mod_id=mozaik
license=LGPLv3
credits=Jared, for the multiloader template
description=mozaik is a cosmetic mod that allows you to discover structures containing remnants of mosaics from long ago and express yourself by creating your own.\n\nExperience a mosaic workstation that allows you to easily replace shards, rotate, flip, save and name your work around using built-in tools. Easily toggle tooltips and adjust sounds in the workstation settings tab according to your preferences.\n\nCraft some shards and some mortar to start the journey.
minecraft_version_range=[1.21.1, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.1-20240808.144430
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.11.10

# Fabric
fabric_version=0.116.17+1.21.1
fabric_loader_version=0.19.3

# NeoForge
neoforge_version=21.1.249
neoforge_loader_version_range=[4,)

# Mods
jei_version=19.51.0.417

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
