# Important Notes:
# Every field you add must be added to buildSrc/src/main/groovy/multiloader-common.gradle expandProps map.

# Project
version=1.0.4
group=com.mod.mozaik
java_version=25

# Common
minecraft_version=26.1.2
mod_name=mozaik
mod_author=zimzelens & jodi/jodlodi
mod_id=mozaik
license=LGPLv3
credits=Jared, for the multiloader template
description=mozaik is a cosmetic mod that allows you to discover structures containing remnants of mosaics from long ago and express yourself by creating your own.\n\nExperience a mosaic workstation that allows you to easily replace shards, rotate, flip, save and name your work around using built-in tools. Easily toggle tooltips and adjust sounds in the workstation settings tab according to your preferences.\n\nCraft some shards and some mortar to start the journey.
minecraft_version_range=[26.1.2, 26.2)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=26.1.2-1

# Fabric, see https://fabricmc.net/develop/ for new versions
fabric_version=0.155.2+26.1.2
fabric_loader_version=0.19.3

# NeoForge, see https://projects.neoforged.net/neoforged/neoforge for new versions
neoforge_version=26.1.2.100
neoforge_loader_version_range=[4,)

# Mods
jei_version=29.34.0.90

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
